# -*- coding: utf-8 -*-
"""Crypto_Game_Theory_intraday.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x2ZwBYGXOWWXJolHAt4ONSrQXR4NQHOk
"""


import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import streamlit as st
from streamlit_autorefresh import st_autorefresh


# Налаштування сторінки в браузері
st.set_page_config(page_title="Game Theory Trader", layout="wide")


# Вставляємо автооновлення на початку (300000 мс = 5 хвилини)
st_autorefresh(interval=300000, key="datarefresh")

st.title("📊 Інтрадей Термінал: Теорія Ігор")
import time
from datetime import datetime, timedelta

# --- БЛОК АВТООНОВЛЕННЯ ТА ТАЙМЕРА ---
refresh_minutes = 5
refresh_seconds = refresh_minutes * 60

# Використовуємо session_state, щоб зберігати час останнього оновлення
if 'last_refresh' not in st.session_state:
    st.session_state.last_refresh = datetime.now()

# Контейнер для таймера (щоб він не "стрибав" по сторінці)
timer_placeholder = st.empty()

# Розрахунок часу до наступного оновлення
now = datetime.now()
time_diff = (now - st.session_state.last_refresh).total_seconds()
remaining = max(0, int(refresh_seconds - time_diff))

if remaining <= 0:
    st.session_state.last_refresh = datetime.now()
    st.rerun() # Перезавантаження сторінки
else:
    # Відображення красивого таймера
    timer_placeholder.caption(f"🕒 Наступне оновлення через: **{remaining // 60:02d}:{remaining % 60:02d}**")

from streamlit_autorefresh import st_autorefresh

# 1. Оновлюємо інтерфейс кожну секунду для "цокання" таймера
st_autorefresh(interval=1000, key="timer_counter")

# 2. Розрахунок залишку часу
if 'next_refresh_time' not in st.session_state:
    st.session_state.next_refresh_time = datetime.now() + timedelta(minutes=4)

remaining_delta = st.session_state.next_refresh_time - datetime.now()
remaining_seconds = int(remaining_delta.total_seconds())

if remaining_seconds <= 0:
    st.session_state.next_refresh_time = datetime.now() + timedelta(minutes=4)
    st.cache_data.clear() # Очищуємо кеш, щоб отримати свіжі дані
    st.rerun()



st.sidebar.header("Налаштування стратегії")

# --- ЕЛЕМЕНТИ КЕРУВАННЯ ---
symbol = st.sidebar.selectbox("Оберіть актив", ["BTC-USD", "ETH-USD", "SOL-USD", "AAPL", "NVDA"])
period = st.sidebar.slider("Період аналізу (дні)", 1, 7, 3)
window = st.sidebar.number_input("Вікно Z-Score (свічки)", value=288)
whale_sens = st.sidebar.slider("Чутливість до китів", 1.5, 4.0, 2.5)

@st.cache_data(ttl=300)
def get_data(symbol, period):
    try:
        # Додаємо auto_adjust=True та примусове скасування MultiIndex
        data = yf.download(symbol, period=f"{period}d", interval='5m', progress=False, auto_adjust=True)
        
        if data.empty:
            return pd.DataFrame()

        # Виправлення структури стовпців (головна причина помилки)
        if isinstance(data.columns, pd.MultiIndex):
            data.columns = data.columns.get_level_values(0)
        
        # Очищуємо від дублікатів та порожніх значень
        data = data.loc[:, ~data.columns.duplicated()].dropna()
        
        return data
    except Exception as e:
        st.error(f"Помилка завантаження: {e}")
        return pd.DataFrame()


# Завантаження
data = get_data(symbol, period)

if not data.empty:
    # --- РОЗРАХУНКИ ---
    # Z-Score
    rolling_mean = data['Close'].rolling(window=window).mean()
    rolling_std = data['Close'].rolling(window=window).std()
    data['Z_Score'] = (data['Close'] - rolling_mean) / rolling_std

    # VWAP
    data['Date_Only'] = data.index.date
    data['VWAP'] = data.groupby('Date_Only', group_keys=False).apply(
        lambda x: (x['Close'] * x['Volume']).cumsum() / x['Volume'].cumsum()
    )

    # Кити та Айсберги
    avg_vol = data['Volume'].rolling(20).mean()
    data['Whale'] = data['Volume'] > (avg_vol * whale_sens)
    price_change = data['Close'].pct_change().abs()
    data['Iceberg'] = (price_change < 0.0005) & (data['Volume'] > avg_vol * 1.8)

    final_df = data.dropna(subset=['Z_Score', 'VWAP']).copy()

    # --- ВІЗУАЛІЗАЦІЯ ---
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(15, 10), sharex=True)
    plt.subplots_adjust(hspace=0.05)

    # 1. Ціна
    ax1.plot(final_df.index, final_df['Close'], label='Ціна', color='#222222', alpha=0.8)
    ax1.plot(final_df.index, final_df['VWAP'], label='VWAP', color='orange', lw=2)

    whales = final_df[final_df['Whale']]
    icebergs = final_df[final_df['Iceberg']]
    ax1.scatter(whales.index, whales['Close'], color='red', label='Whale Signal', s=60, marker='^', zorder=5)
    ax1.scatter(icebergs.index, icebergs['Close'], color='blue', label='Iceberg/Wall', s=60, marker='s', zorder=5)
    ax1.legend(loc='upper left')
    ax1.grid(True, alpha=0.2)

    # 2. Z-Score
    ax2.plot(final_df.index, final_df['Z_Score'], color='purple', label='Z-Score', lw=1.5)
    ax2.axhline(2.5, color='red', ls='--', alpha=0.5)
    ax2.axhline(-2.5, color='green', ls='--', alpha=0.5)
    ax2.fill_between(final_df.index, 2.5, final_df['Z_Score'], where=(final_df['Z_Score'] > 2.5), color='red', alpha=0.2)
    ax2.fill_between(final_df.index, -2.5, final_df['Z_Score'], where=(final_df['Z_Score'] < -2.5), color='green', alpha=0.2)

    # Налаштування дати
    ax2.xaxis.set_major_locator(mdates.HourLocator(interval=1))
    ax2.xaxis.set_major_formatter(mdates.DateFormatter('%H:%M (%d-%m)'))
    plt.xticks(rotation=0)

    # Сітка
    ax2.grid(True, which='major', color='gray', linestyle='-', alpha=0.4)
    ax2.grid(True, which='minor', color='gray', linestyle=':', alpha=0.3)

    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

    # Другорядні мітки (Minor): Кожні 15 хвилин (вертикальні лінії без підписів)
    ax2.xaxis.set_minor_locator(mdates.MinuteLocator(interval=15))
    
    # Вивід у Streamlit
    st.pyplot(fig)

    # --- СТАТИСТИЧНА ПАНЕЛЬ ---
    col1, col2, col3 = st.columns(3)
    last = final_df.iloc[-1]

    with col1:
        st.metric("Поточна ціна", f"${last['Close']:.2f}")
    with col2:
        st.metric("Z-Score (Відхилення)", f"{last['Z_Score']:.2f}")
    with col3:
        status = "⚖️ Рівновага"
        if last['Z_Score'] > 2.5: status = "🔔 ПРОДАЖ (Перегрів)"
        if last['Z_Score'] < -2.5: status = "🔔 КУПІВЛЯ (Паніка)"
        st.subheader(status)

    if last['Whale']:
        st.warning("🐳 Виявлено активність кита на останній свічці!")
    if last['Iceberg']:
        st.info("🧊 Виявлено ознаки 'Айсберга' (прихованої стінки)!")

else:
    st.error("Не вдалося завантажити дані. Перевірте з'єднання або тікер.")
